services:
  app:
    build:
      context: .
      target: final
    restart: always
    env_file:
      - .env
    links:
      - postgres
    ports:
      - '127.0.0.1:${APP_PORT}:${APP_PORT}'
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    ports:
      - '127.0.0.1:${DB_PORT}:${DB_PORT}'
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres:
    driver: local
